name: CI
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Run linting
        run: |
          dotnet tool install --global dotnet-format
          dotnet format --verify-no-changes